# Generated by Django 4.1.7 on 2024-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_de_validacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_0',
            field=models.IntegerField(choices=[(1, 'Espera'), (2, 'Análise'), (3, 'Aceite'), (4, 'Rejeitado')], default=1),
        ),
    ]
