# Generated by Django 4.1.7 on 2024-04-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('acao', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'acao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_de_sala', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocenteUc',
            fields=[
                ('docenteutilizadorid', models.OneToOneField(db_column='DocenteUtilizadorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.docente')),
            ],
            options={
                'db_table': 'docente_uc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('edificio', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'edificio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=255, null=True)),
            ],
            options={
                'db_table': 'estado_sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=255)),
                ('data_h', models.DateField(blank=True, null=True)),
                ('hora_inicial', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('antigodata_h', models.DateField(blank=True, null=True)),
                ('antigohora_inicial', models.TimeField(blank=True, null=True)),
                ('antigohora_final', models.TimeField(blank=True, null=True)),
                ('antigodescricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_instituicao', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'instituicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data_de_submissao', models.DateField(blank=True, null=True)),
                ('data_de_associacao', models.DateTimeField(blank=True, null=True)),
                ('data_de_validacao', models.DateTimeField(blank=True, null=True)),
                ('data_de_alvo', models.DateField(blank=True, null=True)),
                ('assunto', models.CharField(blank=True, db_column='assunto', max_length=255, null=True)),
                ('informacoes', models.CharField(blank=True, db_column='informacoes', max_length=255, null=True)),
                ('comentarios', models.CharField(blank=True, db_column='comentarios', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('id_estado_da_sala', models.CharField(blank=True, db_column='Estado_Sala_id', max_length=255, null=True)),
                ('id_nome_instituicao', models.CharField(blank=True, db_column='Nome_Instituicao_id', max_length=255, null=True)),
                ('id_nome_edificio', models.CharField(blank=True, db_column='Desc_Edificio_id', max_length=255, null=True)),
                ('id_nome_tipo_sala', models.CharField(blank=True, db_column='Des_Categoria_id', max_length=255, null=True)),
                ('id_tipo_aula', models.CharField(blank=True, db_column='Tipo_sala_id', max_length=255, null=True)),
                ('id_ano_letivo', models.CharField(blank=True, db_column='ano_letivo_id', max_length=255, null=True)),
                ('descricao_sala', models.CharField(blank=True, db_column='Desc_Sala', max_length=255, null=True)),
                ('lotacao', models.CharField(blank=True, db_column='Lotacao_Presencial_Sala', max_length=255, null=True)),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='subpedido_sala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=255, null=True)),
                ('inicio', models.DateTimeField(db_column='inicio')),
                ('fim', models.DateTimeField(db_column='fim')),
                ('id_instituicao', models.CharField(blank=True, db_column='Instituicao_id', max_length=255, null=True)),
                ('id_edificio', models.CharField(blank=True, db_column='Edificio_id', max_length=255, null=True)),
                ('id_sala', models.CharField(blank=True, db_column='Sala_id', max_length=255, null=True)),
                ('id_tipo_de_aula', models.CharField(blank=True, db_column='Tipo_de_aula_id', max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, db_column='categoria', max_length=255, null=True)),
                ('numero_alunos', models.CharField(blank=True, db_column='Numero_Alunos', max_length=255, null=True)),
                ('acao', models.CharField(blank=True, db_column='Acao', max_length=255, null=True)),
                ('editar_inicio', models.DateTimeField(db_column='nova_inicio')),
                ('editar_descricao', models.CharField(blank=True, db_column='nova_descricao', max_length=255, null=True)),
                ('editar_fim', models.DateTimeField(db_column='nova_fim')),
                ('editar_id_instituicao', models.CharField(blank=True, db_column='nova_Instituicao_id', max_length=255, null=True)),
                ('editar_id_edificio', models.CharField(blank=True, db_column='nova_Edificio_id', max_length=255, null=True)),
                ('editar_id_sala', models.CharField(blank=True, db_column='nova_Sala_id', max_length=255, null=True)),
                ('editar_id_tipo_de_aula', models.CharField(blank=True, db_column='nova_Tipo_de_aula_id', max_length=255, null=True)),
                ('editar_categoria', models.CharField(blank=True, db_column='nova_categoria', max_length=255, null=True)),
                ('editar_numero_alunos', models.CharField(blank=True, db_column='nova_Numero_Alunos', max_length=255, null=True)),
            ],
            options={
                'db_table': 'subpedido_sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeAulas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_aula', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_de_aulas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uc',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, db_column='Period', max_length=255, null=True)),
                ('codigo', models.IntegerField(blank=True, db_column='Codigo', null=True)),
                ('disciplina', models.CharField(blank=True, db_column='Disciplina', max_length=255, null=True)),
                ('inst_discip', models.CharField(blank=True, db_column='Inst_discip', max_length=255, null=True)),
                ('inst_disciplina_full', models.CharField(blank=True, db_column='Inst_disciplina_full', max_length=255, null=True)),
                ('depart_disciplina', models.CharField(blank=True, db_column='Depart_disciplina', max_length=255, null=True)),
                ('turma', models.CharField(blank=True, db_column='Turma', max_length=255, null=True)),
                ('codigo_curso', models.IntegerField(blank=True, db_column='Codigo_curso', null=True)),
                ('curso', models.CharField(blank=True, db_column='Curso', max_length=255, null=True)),
                ('horas_semanais', models.IntegerField(blank=True, null=True)),
                ('horas_periodo', models.IntegerField(blank=True, null=True)),
                ('horas_servico', models.IntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdentificadorPedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'identificador_pedido',
            },
        ),
        migrations.CreateModel(
            name='TipoDePedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_de_pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoDeHorario',
            fields=[
                ('pedido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pedidos.pedido')),
            ],
            options={
                'db_table': 'pedido_de_horario',
                'managed': False,
            },
            bases=('pedidos.pedido',),
        ),
        migrations.CreateModel(
            name='PedidoDeSala',
            fields=[
                ('pedido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pedidos.pedido')),
            ],
            options={
                'db_table': 'pedido_de_sala',
            },
            bases=('pedidos.pedido',),
        ),
        migrations.CreateModel(
            name='PedidoOutros',
            fields=[
                ('pedido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pedidos.pedido')),
            ],
            options={
                'db_table': 'pedido_outros',
            },
            bases=('pedidos.pedido',),
        ),
        migrations.CreateModel(
            name='PedidoUc',
            fields=[
                ('pedido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pedidos.pedido')),
            ],
            options={
                'db_table': 'pedido_uc',
            },
            bases=('pedidos.pedido',),
        ),
        migrations.CreateModel(
            name='SubpedidoUc',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ucid', models.CharField(db_column='ucid', max_length=255)),
                ('descricao', models.CharField(db_column='descricao', max_length=255)),
                ('acao', models.CharField(db_column='acao', max_length=255)),
                ('turma', models.CharField(db_column='turma', max_length=255)),
                ('pedido_ptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidodehorario')),
            ],
            options={
                'db_table': 'subpedido_uc',
            },
        ),
        migrations.CreateModel(
            name='Outros',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Assunto', models.CharField(max_length=255)),
                ('Descricao', models.CharField(max_length=500)),
                ('pedido_ptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidooutros')),
            ],
            options={
                'db_table': 'outros',
            },
        ),
    ]
