# Generated by Django 4.1.7 on 2024-04-20 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tema', models.CharField(choices=[('Tempo do Pedido', 'Tempo do Pedido'), ('Pedido', 'Pedido'), ('Responsável', 'Responsável'), ('Outro', 'Outro')], default='Outro', max_length=50)),
            ],
            options={
                'db_table': 'pergunta',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('data_limite', models.DateField()),
                ('estado', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Arquivado', 'Arquivado')], default='ativo', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'questionario',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='pedidos.pergunta')),
            ],
            options={
                'db_table': 'resposta',
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='pedidos.questionario'),
        ),
    ]
