# Generated by Django 4.1.7 on 2024-04-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pergunta_questionario_resposta_pergunta_questionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='estado',
        ),
    ]
