# Generated by Django 4.1.7 on 2024-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_questionario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_questionario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estado_questionario',
                'managed': False,
            },
        ),
    ]
