# Generated by Django 4.1.7 on 2024-04-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_estadoquestionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoQuestionario',
        ),
    ]
