# Generated by Django 4.1.7 on 2024-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_delete_estadoquestionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoQuestionario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=255, null=True)),
            ],
            options={
                'db_table': 'estado_questionario',
                'managed': False,
            },
        ),
    ]
