# Generated by Django 4.1.7 on 2024-04-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_estadoquestionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoquestionario',
            options={},
        ),
        migrations.AddField(
            model_name='questionario',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.estadoquestionario'),
        ),
    ]
