# Generated by Django 4.1.7 on 2024-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_estadoquestionario_options_questionario_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='estado',
        ),
        migrations.AlterField(
            model_name='estadoquestionario',
            name='estado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estadoquestionario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
