# Generated by Django 4.1.7 on 2024-04-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_questionario_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Questionario',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
