# Generated by Django 4.1.7 on 2024-04-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_remove_resposta_pergunta_delete_pergunta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoQuestionario',
        ),
    ]
