# Generated by Django 4.1.7 on 2024-04-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pergunta_resposta_questionario_pergunta_questionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeInvestigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
