# Generated by Django 4.1.7 on 2024-04-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedidodeparecer_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodeparecer',
            name='estado',
        ),
    ]
