# Generated by Django 4.1.7 on 2024-04-20 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_pedidodeparecer_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeparecer',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.estadopedido'),
        ),
    ]
