# Generated by Django 4.1.7 on 2024-04-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0022_pedidodeparecer_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodeparecer',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.estadopedido'),
        ),
    ]
