# Generated by Django 4.1.7 on 2024-04-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_remove_pedidodeparecer_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodeparecer',
            name='centro_de_investigacao',
        ),
        migrations.RemoveField(
            model_name='pedidodeparecer',
            name='solicitante',
        ),
        migrations.DeleteModel(
            name='CentroDeInvestigacao',
        ),
        migrations.DeleteModel(
            name='PedidoDeParecer',
        ),
    ]
