# Generated by Django 4.1.7 on 2024-04-22 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0025_remove_pedidodeparecer_centro_de_investigacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDeParecer',
            fields=[
                ('pedido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pedidos.pedido')),
                ('parecer', models.TextField(blank=True, null=True)),
                ('documentos_anexos', models.FileField(blank=True, null=True, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'db_table': 'pedido_de_parecer',
            },
            bases=('pedidos.pedido',),
        ),
    ]
