# Generated by Django 4.1.7 on 2024-05-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0027_estudante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudante',
        ),
        migrations.RemoveField(
            model_name='pedidodeparecer',
            name='pedido_ptr',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='questionario',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.DeleteModel(
            name='EstadoQuestionario',
        ),
        migrations.DeleteModel(
            name='PedidoDeParecer',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Questionario',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
