# Generated by Django 4.1.7 on 2024-05-17 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0029_estadoquestionario_pedidodeparecer_pergunta_resposta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Assunto', models.CharField(max_length=255)),
                ('Descricao', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='PedidoDeAluno',
            fields=[
                ('pedido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pedidos.pedido')),
            ],
            options={
                'db_table': 'pedido_de_aluno',
            },
            bases=('pedidos.pedido',),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tema',
            },
        ),
        migrations.RemoveField(
            model_name='pedidodeparecer',
            name='pedido_ptr',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='opcao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='opcao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='opcao3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='opcao4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='opcao5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='opcao6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('texo', 'texto'), ('multipla', 'multipla')], default='texto', max_length=20),
        ),
        migrations.AddField(
            model_name='questionario',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='questionario',
            name='id_ano_letivo',
            field=models.CharField(blank=True, db_column='ano_letivo_id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='valido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='estado',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Arquivado', 'Arquivado')], default='ativo', max_length=20),
        ),
        migrations.DeleteModel(
            name='EstadoQuestionario',
        ),
        migrations.DeleteModel(
            name='PedidoDeParecer',
        ),
        migrations.AddField(
            model_name='aluno',
            name='pedido_ptr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidodealuno'),
        ),
    ]
