# Generated by Django 4.1.7 on 2024-05-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0031_estadoquestionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.estadoquestionario'),
        ),
    ]
