# Generated by Django 4.1.7 on 2024-05-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0032_alter_questionario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='pedidos.tema'),
        ),
    ]
