# Generated by Django 4.1.7 on 2024-05-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0033_pergunta_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='valor',
        ),
        migrations.AddField(
            model_name='resposta',
            name='resposta_opcao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='resposta_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
