# Generated by Django 4.1.7 on 2024-06-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0038_pedidodeparecer_delete_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadopedido',
            options={'managed': True},
        ),
    ]
