# Generated by Django 4.1.7 on 2024-06-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0039_alter_estadopedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopedido',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
