# Generated by Django 4.1.7 on 2024-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regencia',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('regencia_id', models.IntegerField(db_column='regencia_id')),
            ],
            options={
                'db_table': 'regencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('curso_nome', models.CharField(blank=True, db_column='curso_nome', max_length=255, null=True)),
                ('ciclo', models.IntegerField(db_column='ciclo')),
                ('codigo', models.IntegerField(db_column='codigo')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='TipoDeRegencia',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='tipo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_de_regencia',
            },
        ),
    ]
